---
Name: headjs
After:
  - 'framework/*'
  - 'cms/*'
---
HeadJsBackend:
    cdnSource: http://cdnjs.cloudflare.com/ajax/libs/headjs/1.0.3/head.min.js
    javascriptSource: /headjs/javascript/head.min.js